#!/bin/sh
# Give a battery name (e.g. BAT0) as an argument.

BAT="${BAT:-$1}"
BAT="${BAT:-BAT0}"

# get xresources colors
for x in "$(xrdb -query | sed "s/.*\./export /g;s/:\s*/=\"/g;s/$/\"/g")"; do eval "$x"; done

case $BLOCK_BUTTON in
3) pgrep -x dunst >/dev/null && notify-send "🔋 Battery module:
🔋: discharging
♻: stagnant charge
🔌: charging
⚡: charged
❗: battery very low!
- Text color reflects charge left" ;;
esac

capacity=$(cat /sys/class/power_supply/BAT0/capacity) || exit
status=$(cat /sys/class/power_supply/BAT0/status)
CHARGING="Charging"
DISCHARGING="Discharging"

icon='🔋'
fg="#928374"

if [ "$capacity" -ge 99 ]; then
	fg="#928374"
	if [ $status == $CHARGING ]; then
		icon='󱊦  '
	else
		icon='󱊣'
	fi
elif [ "$capacity" -ge 90 ]; then
	fg="#928374"
	if [ $status == $CHARGING ]; then
		icon='󱊦 '
	else
		icon='󰂂'
	fi
elif [ "$capacity" -ge 65 ]; then
	fg="#928374"
	if [ $status == $CHARGING ]; then
		icon='󱊥 '
	else
		icon='󰁿'
	fi
elif [ "$capacity" -ge 40 ]; then
	fg="#928374"
	if [ $status == $CHARGING ]; then
		icon='󰢝 '
	else
		icon='󰁽'
	fi
elif [ "$capacity" -ge 15 ]; then
	fg="#d79921"
	if [ $status == $CHARGING ]; then
		icon='󱊤 '
	else
		icon='󰁻'
	fi
else
	fg="#fb4934"
	if [ $status == $CHARGING ]; then
		icon='󰢟 '
	else
		icon='󰁺'
	fi
fi

echo "<span foreground='$fg'>$icon$capacity%</span>"
