[tools]
nodejs = "latest"
golang = "latest"
python = "3.13"
bun    = "latest"
deno   = "latest"
lua    = "5.4.4"
pnpm   = "latest"
java   = "latest"
yarn  = "latest"
usage = "latest"
go = "latest"
node = "latest"


# This was a quick fix for corepack false positives.
# I'm not using corepack any more. Uncomment if needed in feature
# yarn   = "1.22.0" # pin it till the issue is resolved https://github.com/yarnpkg/yarn/issues/9015
