#!/usr/bin/env bash

# Patch for known bug: A spurious warning is issued when unstowing a package #65
# https://github.com/aspiers/stow/issues/65#issuecomment-757644763
function stow_patch() {
    stow $@ 2>&1 | grep -v "BUG in find_stowed_path? Absolute/relative mismatch between Stow dir .dot and path"
}

for folder in */
do
    if [ $folder != '_init/' ]
    then
        echo "Removing $folder"
        stow_patch -D $folder
    fi
done
# vim: ft=bash
