#!/bin/sh
#
# This is git hook.
# It need to be symlinked to git/hooks/commit-msg`
# Its purpose is to prepare git commit message.
# Message will be prefixed with with name of main group, of edited files.
# Dotfiles are grouped into folders in root of repository (one level deep).
# It'll fail when files from multiple groups are commited. In that case split
# them into multiple commits.


# echo "_commitMsg_" > $1

# git diff --cached --name-only -r
git diff --cached --name-only --diff-filter=ACM

