[directory]
truncate_to_repo          = false
truncation_length         = 3
fish_style_pwd_dir_length = 1
truncation_symbol         = "…/"
style                     = "#8ec07c bold"

[username]
show_always = true 
style_user  = "#b16286 bold"
style_root  = "#cc241d bold"
format      = "[$user]($style)"
disabled    = false

[hostname]
ssh_only = false
format   =  "@[$hostname](bold #f65d0e) "
disabled = false

[git_branch]
style = "#458588 bold"

[git_status]
style      = "bold white"
format     = '([\($all_status$ahead_behind\)]($style) )'
conflicted = "[=](#cc241d bold)"
ahead      = "[⇡](#98971a bold)"
behind     = "[⇣](#cc241d bold)"
diverged   = "[⇕](#cc241d bold)"
up_to_date = ""
untracked  = "[?](#cc241d bold)"
stashed    = "[$](#f65d0e bold)"
modified   = "[!](#cc241d bold)"
staged     = "[+](#98971a bold)"
renamed    = "[»](#cc241d bold)"
deleted    = "[✘](#cc241d bold)"
disabled   = false
