require('keymaps.general')

require('keymaps.lsp')
require('keymaps.spell')
require('keymaps.edit-myvimrc')
require('keymaps.harpoon')
require('keymaps.vim-yoink')
require('keymaps.trouble')
require('keymaps.vimux')
require('keymaps.reload_config')
