require('keymaps.general') -- always first

require('keymaps.edit-myvimrc')
require('keymaps.harpoon')
require('keymaps.lsp')
require('keymaps.spell')
require('keymaps.telescope')
require('keymaps.trouble')
require('keymaps.vim-yoink')
require('keymaps.vimux')
require('keymaps.windows-and-tabs')
require('keymaps.typescript-nvim')
require('keymaps.lazygit')
require('keymaps.nvim-tree')
require('keymaps.bufferline')
require('keymaps.vim-bbye')
require('keymaps.tabular')
require('keymaps.fugitive')
