require("keymaps.general")

require("keymaps.edit-myvimrc")
require("keymaps.harpoon")
require("keymaps.lsp")
require("keymaps.reload_config")
require("keymaps.spell")
require("keymaps.telescope")
require("keymaps.trouble")
require("keymaps.vim-yoink")
require("keymaps.vimux")
require("keymaps.windows-and-tabs")
require("keymaps.typescript-nvim")
require("keymaps.lazygit")
