# yaml-language-server: $schema=https://raw.githubusercontent.com/jesseduffield/lazygit/master/schema/config.json
gui:
  branchColorPatterns:
    "^vim$": "#11AAFF"
    "^zsh$": "#CF97FF"
    "^tmux$": "#98FFD5"
    "^i3$": "#FF9DD6"
  authorColors: {}
  customIcons:
    filenames: {}
    extensions: {}
  scrollHeight: 5
  scrollPastBottom: true
  scrollOffMargin: 2
  scrollOffBehavior: margin
  sidePanelWidth: 0.3333
  expandFocusedSidePanel: true
  expandedSidePanelWeight: 2
  mainPanelSplitMode: flexible
  enlargedSideViewLocation: left
  language: en
  timeFormat: "02 Jan 06 15:04 MST"
  shortTimeFormat: 3:04PM
  tabWidth: 4
  wrapLinesInStagingView: true
  useHunkModeInStagingView: true
  theme:
    activeBorderColor:
      - green
      - bold
    inactiveBorderColor:
      - white
    searchingActiveBorderColor:
      - cyan
      - bold
    optionsTextColor:
      - blue
    selectedLineBgColor:
      - blue
    cherryPickedCommitFgColor:
      - blue
    markedBaseCommitFgColor:
      - blue
    markedBaseCommitBgColor:
      - yellow
    unstagedChangesColor:
      - red
    defaultFgColor:
      - default
    inactiveViewSelectedLineBgColor:
      - bold
  commitLength:
    show: true
  mouseEvents: true
  skipAmendWarning: false
  skipDiscardChangeWarning: false
  skipStashWarning: false
  skipNoStagedFilesWarning: false
  skipRewordInEditorWarning: false
  skipSwitchWorktreeOnCheckoutWarning: false
  showFileTree: true
  showRootItemInFileTree: true
  fileTreeSortOrder: mixed
  fileTreeSortCaseSensitive: true
  showNumstatInFilesView: false
  showListFooter: true
  showRandomTip: false
  showBottomLine: true
  showPanelJumps: true
  showCommandLog: true
  showFileIcons: true
  nerdFontsVersion: "3"
  commitAuthorShortLength: 2
  commitAuthorLongLength: 17
  commitHashLength: 8
  showBranchCommitHash: false
  showDivergenceFromBaseBranch: none
  commandLogSize: 8
  splitDiff: auto
  screenMode: normal
  border: rounded
  animateExplosion: true
  portraitMode: auto
  portraitModeAutoMaxWidth: 84
  portraitModeAutoMinHeight: 46
  filterMode: substring
  spinner:
    frames:
      - "|"
      - /
      - "-"
      - \
    rate: 50
  statusPanelView: dashboard
  switchToFilesAfterStashPop: true
  switchToFilesAfterStashApply: true
  switchTabsWithPanelJumpKeys: false

git:
  pagers:
    - colorArg: always
      pager: ""
      externalDiffCommand: ""
      useExternalDiffGitConfig: false
  commit:
    signOff: false
    autoWrapCommitMessage: true
    autoWrapWidth: 72
  merging:
    manualCommit: false
    args: ""
    squashMergeMessage: "Squash merge {{selectedRef}} into {{currentBranch}}"
  mainBranches:
    - master
    - main
  skipHookPrefix: WIP
  autoFetch: true
  autoRefresh: true
  autoForwardBranches: onlyMainBranches
  fetchAll: true
  autoStageResolvedConflicts: true
  branchLogCmd: "git log --graph --color=always --abbrev-commit --decorate --date=relative --pretty=medium {{branchName}} --"
  allBranchesLogCmds:
    - git log --graph --all --color=always --abbrev-commit --decorate --date=relative --pretty=medium
  ignoreWhitespaceInDiffView: false
  diffContextSize: 3
  renameSimilarityThreshold: 50
  overrideGpg: false
  disableForcePushing: false
  parseEmoji: false
  commitPrefix: []
  commitPrefixes: {}
  branchPrefix: ""
  truncateCopiedCommitHashesTo: 12
  log:
    order: topo-order
    showGraph: always
    showWholeGraph: false
  localBranchSortOrder: date
  remoteBranchSortOrder: date

update:
  method: never
  days: 14

refresher:
  refreshInterval: 5
  fetchInterval: 60

confirmOnQuit: false
quitOnTopLevelReturn: true
disableStartupPopups: true
notARepository: prompt
promptToReturnFromSubprocess: false

os:
  edit: ""
  editAtLine: ""
  editAtLineAndWait: ""
  editInTerminal: false
  openDirInEditor: ""
  editPreset: "nvim-remote"
  open: ""
  openLink: ""
  copyToClipboardCmd: ""
  readFromClipboardCmd: ""
  shellFunctionsFile: ""

customCommands: []
services: {}

keybinding:
  universal:
    quit: [q]
    suspendApp: <ctrl+z>
    return: <esc>
    quitWithoutChangingDirectory: Q
    togglePanel: <tab>
    prevItem: [<up>, k]
    nextItem: [<down>, j]
    prevPage: ","
    nextPage: .
    scrollLeft: H
    scrollRight: L
    gotoTop: [<, <home>]
    gotoBottom: [">", <end>]
    toggleRangeSelect: v
    rangeSelectDown: <shift+down>
    rangeSelectUp: <shift+up>
    prevBlock: [<left>, h, <backtab>]
    nextBlock: [<right>, l, <tab>]
    jumpToBlock:
      - "1"
      - "2"
      - "3"
      - "4"
      - "5"
    focusMainView: "0"
    nextMatch: n
    prevMatch: N
    startSearch: /
    moveWordLeft: <ctrl+left>
    moveWordRight: <ctrl+right>
    backspaceWord: <ctrl+backspace>
    forwardDeleteWord: <ctrl+delete>
    optionMenu: "?"
    select: <space>
    goInto: <enter>
    confirm: <enter>
    confirmMenu: <enter>
    confirmSuggestion: <enter>
    confirmInEditor: [<ctrl+enter>, <ctrl+s>]
    remove: d
    new: "n"
    edit: e
    openFile: o
    scrollUpMain: [<pgup>, K, <ctrl+u>]
    scrollDownMain: [<pgdown>, J, <ctrl+d>]
    executeShellCommand: ":"
    createRebaseOptionsMenu: b
    pushFiles: P
    pullFiles: p
    refresh: R
    createPatchOptionsMenu: <ctrl+p>
    nextTab: "]"
    prevTab: "["
    nextScreenMode: +
    prevScreenMode: _
    cyclePagers: "|"
    undo: z
    redo: Z
    filteringMenu: <ctrl+s>
    diffingMenu: [W, <ctrl+e>]
    copyToClipboard: <ctrl+o>
    openRecentRepos: <ctrl+r>
    submitEditorText: <enter>
    extrasMenu: "@"
    toggleWhitespaceInDiffView: <ctrl+w>
    increaseContextInDiffView: "}"
    decreaseContextInDiffView: "{"
    increaseRenameSimilarityThreshold: )
    decreaseRenameSimilarityThreshold: (
    openDiffTool: <ctrl+t>
  status:
    checkForUpdate: u
    recentRepos: <enter>
    allBranchesLogGraph: a
    allBranchesLogGraphReverse: A
  files:
    commitChanges: c
    commitChangesWithoutHook: w
    amendLastCommit: A
    commitChangesWithEditor: C
    findBaseCommitForFixup: <ctrl+f>
    confirmDiscard: x
    ignoreFile: i
    refreshFiles: r
    stashAllChanges: s
    viewStashOptions: S
    toggleStagedAll: a
    viewResetOptions: D
    fetch: f
    toggleTreeView: "`"
    openMergeOptions: M
    openStatusFilter: <ctrl+b>
    copyFileInfoToClipboard: "y"
    collapseAll: "-"
    expandAll: "="
  branches:
    createPullRequest: o
    viewPullRequestOptions: O
    openPullRequestInBrowser: G
    copyPullRequestURL: <ctrl+y>
    checkoutBranchByName: c
    forceCheckoutBranch: F
    checkoutPreviousBranch: "-"
    rebaseBranch: r
    renameBranch: R
    mergeIntoCurrentBranch: M
    moveCommitsToNewBranch: "N"
    viewGitFlowOptions: i
    fastForward: f
    createTag: T
    pushTag: P
    setUpstream: u
    fetchRemote: f
    addForkRemote: F
    sortOrder: s
  commits:
    squashDown: s
    renameCommit: r
    renameCommitWithEditor: R
    viewResetOptions: g
    markCommitAsFixup: f
    setFixupMessage: c
    createFixupCommit: F
    squashAboveCommits: S
    moveDownCommit: <disabled>
    moveUpCommit: <disabled>
    amendToCommit: A
    resetCommitAuthor: a
    pickCommit: p
    revertCommit: t
    cherryPickCopy: c
    pasteCommits: v
    markCommitAsBaseForRebase: B
    tagCommit: T
    checkoutCommit: <space>
    resetCherryPick: <ctrl+r>
    copyCommitAttributeToClipboard: <ctrl+y>
    openLogMenu: <ctrl+l>
    openInBrowser: o
    openPullRequestInBrowser: G
    viewBisectOptions: b
    startInteractiveRebase: i
    selectCommitsOfCurrentBranch: "*"
  amendAttribute:
    resetAuthor: a
    setAuthor: A
    addCoAuthor: c
  stash:
    popStash: g
    renameStash: r
  commitFiles:
    checkoutCommitFile: c
  main:
    prevHunk: [<left>, h]
    nextHunk: [<right>, l]
    toggleSelectHunk: a
    pickBothHunks: b
    editSelectHunk: E
  submodules:
    init: i
    update: u
    bulkMenu: b
  commitMessage:
    commitMenu: <ctrl+o>
