import { Type } from "typebox";
import type { ExtensionAPI } from "@earendil-works/pi-coding-agent";
import type { BrowserManager } from "./browser";
import { extractFromPage } from "./extractor";

const DEFAULT_MAX_CHARS = 8000;
const NAVIGATION_TIMEOUT_MS = 30000;

const parametersSchema = Type.Object({
  url: Type.String({
    description: "URL to fetch, e.g. https://example.com or http://localhost:8448",
  }),
  maxChars: Type.Optional(
    Type.Number({
      description: "Maximum characters to return. Defaults to 8000.",
      default: DEFAULT_MAX_CHARS,
    }),
  ),
  waitUntil: Type.Optional(
    Type.Union(
      [
        Type.Literal("load"),
        Type.Literal("domcontentloaded"),
        Type.Literal("networkidle"),
      ],
      {
        description:
          "When to consider navigation complete. Use 'networkidle' for SPAs. Defaults to 'networkidle'.",
      },
    ),
  ),
  selector: Type.Optional(
    Type.String({
      description: "Optional CSS selector to extract text from a specific element.",
    }),
  ),
  includeHtml: Type.Optional(
    Type.Boolean({
      description: "Return raw rendered HTML instead of plain text.",
      default: false,
    }),
  ),
});

export function registerRichWebfetch(
  pi: ExtensionAPI,
  browserManager: BrowserManager,
) {
  pi.registerTool({
    name: "rich_webfetch",
    label: "Rich Web Fetch",
    description:
      "Fetch a URL with a headless browser and return rendered content as plain text. Supports JavaScript-generated pages.",
    promptSnippet:
      "Fetch a web page with JavaScript rendering using a headless browser.",
    promptGuidelines: [
      "Use rich_webfetch when the page content is generated by JavaScript (React, Vue, etc.).",
      "Use rich_webfetch for localhost or private pages where static fetch is insufficient.",
      "Use plain webfetch for simple static HTML pages to avoid browser overhead.",
    ],
    parameters: parametersSchema,

    async execute(_toolCallId, params, signal) {
      validateUrl(params.url);

      const page = await browserManager.newPage();

      try {
        await page.goto(params.url, {
          waitUntil: params.waitUntil ?? "networkidle",
          timeout: NAVIGATION_TIMEOUT_MS,
        });

        signal?.throwIfAborted();

        const text = await extractFromPage(page, {
          selector: params.selector,
          includeHtml: params.includeHtml,
          maxChars: params.maxChars ?? DEFAULT_MAX_CHARS,
        });

        return {
          content: [{ type: "text", text }],
          details: { url: params.url, chars: text.length },
        };
      } finally {
        await page.close().catch(() => {});
      }
    },
  });
}

function validateUrl(url: string): void {
  if (!url.startsWith("http://") && !url.startsWith("https://")) {
    throw new Error(
      `Invalid URL: ${url} (must start with http:// or https://)`,
    );
  }
}
